baseURL = 'https://about.jazzofjapan.com'
theme = 'hugo-bearblog'
title = 'About Jazz of Japan'
author = 'Brian McCrory'
copyright = '© Brian McCrory <a href="https://www.jazzofjapan.com">Jazz of Japan</a>'
languageCode = 'en-US'
enableRobotsTXT = true

[frontmatter]
  date = [":filename", ":default"]

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = 'About the Jazz of Japan newsletter and archive'
  favicon = 'favicon.ico'
  hideMadeWithLine = true
  enablePostNavigator = true

[markup]
  [markup.highlight]
    style = 'friendly'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Jazz of Japan"
    url = "https://www.jazzofjapan.com/"
    weight = 100
