#+title: Supporters
#+date: 2026-03-28
#+lastmod: 2026-03-28

* Thank you to all Jazz of Japan supporters!

I'd like to especially thank some premium supporters, present and past, including these fine folks:

-----

/Ray J., Bruce R., Jack L., Ring Flaxen, P. B., Bruce D R., Richard N., Jarmo E., Stregoni, Syd Schwartz [[https://jazzandcoffee.substack.com/][Jazz and Coffee]], Anonymous... *Seriously, thank you!*/

-----

* Like Jazz of Japan? Support this project!

You can sign up for a premium membership through the [[https://buttondown.com/login?subscriber=1][Subscriber portal]], where you can upgrade or change your settings. Or, you can click the “Manage Your Subscription” link at the bottom of any email from Jazz of Japan, or click the “Upgrade” link in the archive.

If you’re not already signed up for the newsletter, enter your email address here: [[https://www.jazzofjapan.com/][Jazz of Japan]].

* Benefits

In addition to the emails that regular subscribers receive through the newsletter, premium subscribers receive occasional bonus emails. While the regular emails are all about Japanese jazz albums, the extra issues are about Japanese jazz clubs, venues, or guides with extra information (and lots of photos) on real modern-day jazz scenes in Japan. I send these premium issues through the newsletter exclusively to premium subscribers about once a month.

Having said that, I’m not interested in using paywalls in the articles. I hope that choosing to upgrade to a premium subscription is a good way to show your personal support for this site and to me. It really means a lot to me and I never take it, or your attention as a reader, for granted.

Subscriptions to Jazz of Japan are USD $5/month (or $50/year) and can be canceled at any time. Payments are handled securely through the Stripe platform, just like on Substack. If there's ever a problem with your subscription, just contact me and I will try to make things right.

* With special thanks to...

I really appreciate the attention and support you send my way. This is a completely human-powered project (just me), and your interest honestly elevates my motivation and momentum. Whether you are a regular reader who subscribes to the newsletter, or someone who shows supports through a paid subscription, or someone who adds a comment or sends a note to just say thanks... you do make a big difference.

If you would like to support Jazz of Japan and have a link you would like to share here (or if you prefer to remain anonymous), please don't hesitate to reach out and let me know.

Thanks,

--Brian
