#+title: J Jazz v2.0 (Substack)
#+date: 2021-05-30
#+draft: false
#+tags[]: versions

/WordPress was becoming an unnecessary hassle, and I found an easier alternative by moving to Substack./

* May 2021: Moving from WordPress to Substack

Substack offered an attractive solution: a simple design that featured newsletter functionality with a nice-looking web archive. The writing interface and dashboard was also refreshingly simple and clean. It was comparatively simple, a great interface to focus on writing and organizing posts.

In 2021, Substack was rapidly changing, enlisting high profile writers and sponsoring growth programs, yet the Substack team still seemed to have an independent startup freshness. Their support and outreach team was involved in weekly community discussions and enthusiastic to hear ideas from, and grow with, their writers. The platform was growing, but it was still all about writing newsletters.

Although I didn’t initially have the goal of starting a newsletter, I decided to give it a try. But honestly, the main attraction at this time was finding a way to use the Substack web archive as a replacement for the WordPress posts that I had been writing. It was free to do this on Substack. It was also a simpler replacement for the WordPress instance I had to both run on my laptop and maintain somewhere in the cloud, at some cost.

Compared to WordPress, the Substack system was simpler, cleaner, and included built-in benefits like an archive of posts and search functionality. With Substack, these were free, standard parts of the system, without having to choosing, configuring, or maintaining different plugins, themes, databases, configurations, updates, etc.

To move my articles from WordPress to Substack, I used Substack’s migration tool to import all the posts from WordPress to Substack. The import wasn’t perfect, and I had to do some manual fixes after the import, but it was manageable.

In May 2021, after importing, cleaning, and organizing my articles on Substack, I published the new “J Jazz” Substack on [[https://web.archive.org/web/20210522222118/https://jjazz.substack.com/][=jjazz.substack.com=]] (no longer in use).

Next, I began to send out new newsletter emails for “Albums” articles on a regular basis, and continued to publish 200+ articles about Japanese jazz albums.

I used Substack for the second phase of this project until about a year later on January 21, 2022. After this, I migrated the newsletter archive to a static page site using GitHub and Jekyll, closed my `jjazz` Substack account, and retired the newsletter (temporarily).
