# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

# removed everything here, so that any checkins to this repo will not auto-build and deploy (which wipes out other builds I may have deployed here to the pages site for brianmccrory.github.io)
