name: Build with markdown export and Deploy
on:
  push:
    branches: ["main"]
  workflow_dispatch:


permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      
      - name: Install emacs-nox
        run: sudo apt install emacs-nox --yes

      - name: Build site (build.sh)
        run: ./build.sh 

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: p
