name: Build with markdown export and Deploy
on:
  push:
    branches:
      - main
      
permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      
      - name: Install emacs-nox
        run: sudo apt install emacs-nox --yes

      - name: Build site (build.sh)
        run: ./build.sh 

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
